"""Added price, rating, and review fields

Revision ID: 514fe658b614
Revises: ca46f4a17bfa
Create Date: 2025-06-25 18:31:04.905457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514fe658b614'
down_revision = 'ca46f4a17bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.JSON(), nullable=True))

    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_item', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('price')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('review')

    # ### end Alembic commands ###
