"""Added user roles and bio, fixed model order

Revision ID: 5859dd7f370e
Revises: 514fe658b614
Create Date: 2025-06-25 19:05:49.233767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5859dd7f370e'
down_revision = '514fe658b614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
